# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-10 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, upload_to='profile_image')),
                ('username', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=100, null=True)),
                ('contacts', models.CharField(max_length=30)),
            ],
        ),
    ]
